#!/bin/sh
#
# Script generated by ./bin/save-vscode-extensions. DO NOT EDIT.
#
# Fri Mar  8 10:14:14 PST 2019
#

code --install-extension andyyaldoo.vscode-json
code --install-extension aws-scripting-guy.cform
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Compulim.indent4to2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension GrapeCity.gc-excelviewer
code --install-extension letmaik.git-tree-compare
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nopjmp.fairyfloss
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension xaver.clang-format
code --install-extension zxh404.vscode-proto3
